spring:
  application:
    name: b2c-mybatis
  datasource:
    url: jdbc:mysql://localhost:3306/sakila?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    password: root
    username: root
server:
  port: 9989
info:
  service-name: ${spring.application.name}
  ip: ${spring.cloud.client.ip-address}
  env: ${active.profile.name}
  system: ${os.name}